### ISSUE TITLE
Swift integration example

### ISSUE THREAD

**Issue by mckayryane** [eWAYPayment/eWAYPaymentsSDK#2]
Are you planning to add swift example?

**Comment by macleancherry** [comment]
Hi @mckayryane I've sent this through to our dev team and we'll look to get an example up soon. Thanks for the request.

**Comment by mckayryane** [comment]
Hi @macleancherry any progress? Thanks

**Comment by macleancherry** [comment]
Hi @mckayryane it's been written, just going through QA and we'll release this week for you.

**Comment by macleancherry** [comment]
@mckayryane you can now see the example in this gist - https://gist.github.com/incarnate/294476023d38944bc2e1 We'll get it up the website at a later stage.
